export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';

export const SAVE_REQUESTING = 'SAVE_REQUESTING';
export const SAVE_SUCCESS = 'SAVE_SUCCESS';
export const SAVE_FAILURE = 'SAVE_FAILURE';

export const LIST_AWB_REQUESTING = 'LIST_AWB_REQUESTING';
export const LIST_AWB_SUCCESS = 'LIST_AWB_SUCCESS';
export const LIST_AWB_FAILURE = 'LIST_AWB_FAILURE';

export const SNACKBAR_SUCCESS = 'SNACKBAR_SUCCESS';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
// export const PREVIEW_IMAGE = 'jpg,png';